name: personalized_rehabilitation_plans
description: A personalized rehabilitation plan application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  
  # Firebase - using compatible versions that work together
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  
  # State management
  provider: ^6.0.5
  
  # HTTP
  http: ^0.13.5
  circular_countdown_timer: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true