// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8g6zHEEbPxcX0J_VVMCmbFIwfGsowRQY',
    appId: '1:188510725049:web:6b13cab430cba9e3468c68',
    messagingSenderId: '188510725049',
    projectId: 'prp-60374',
    authDomain: 'prp-60374.firebaseapp.com',
    storageBucket: 'prp-60374.firebasestorage.app',
    measurementId: 'G-C44H7Z3LJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA4lWK4Bb4quITCWNPMxQe8oXswzd7O2A',
    appId: '1:188510725049:android:e84932030c04313b468c68',
    messagingSenderId: '188510725049',
    projectId: 'prp-60374',
    storageBucket: 'prp-60374.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfiooHToKQbwhZonm4zKpI9K4C21Cn_GY',
    appId: '1:188510725049:ios:42149c44550ad409468c68',
    messagingSenderId: '188510725049',
    projectId: 'prp-60374',
    storageBucket: 'prp-60374.firebasestorage.app',
    iosBundleId: 'com.example.personalizedRehabilitationPlans',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfiooHToKQbwhZonm4zKpI9K4C21Cn_GY',
    appId: '1:188510725049:ios:42149c44550ad409468c68',
    messagingSenderId: '188510725049',
    projectId: 'prp-60374',
    storageBucket: 'prp-60374.firebasestorage.app',
    iosBundleId: 'com.example.personalizedRehabilitationPlans',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8g6zHEEbPxcX0J_VVMCmbFIwfGsowRQY',
    appId: '1:188510725049:web:86b0745112a2dd34468c68',
    messagingSenderId: '188510725049',
    projectId: 'prp-60374',
    authDomain: 'prp-60374.firebaseapp.com',
    storageBucket: 'prp-60374.firebasestorage.app',
    measurementId: 'G-3KZKX71NPL',
  );

}